# Generated by Django 5.2.7 on 2025-11-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                (
                    "start_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the conversation was started"
                    ),
                ),
                (
                    "end_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the conversation was manually ended or archived",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("ended", "Ended")],
                        default="active",
                        help_text="The current status of the conversation (e.g., active, ended)",
                        max_length=10,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the conversation.",
                        null=True,
                    ),
                ),
                (
                    "key_points",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated key points, as a bulleted list or JSON.",
                        null=True,
                    ),
                ),
                (
                    "vector_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embedding of the conversation summary for semantic search.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was created."
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The parent conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
