# Generated by Django.
# This migration loads data from a JSON fixture file.

from django.db import migrations
from django.core.management import call_command

# --- REMOVED THE COMPLEX PATHLIB LOGIC ---

def load_data(apps, schema_editor):
    """
    Loads the sample_data.json fixture file into the database.
    We just need to provide the name, and Django will find it
    in our 'chat/fixtures/' directory.
    """
    # --- THIS IS THE FIX ---
    call_command(
        'loaddata',
        'sample_data.json' # Just use the fixture name
    )
    # --- END OF FIX ---

def reverse_data(apps, schema_editor):
    """
    Defines how to "un-do" this migration. We'll just delete all data.
    """
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')
    db_alias = schema_editor.connection.alias
    
    Conversation.objects.using(db_alias).all().delete()
    Message.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'), 
    ]

    operations = [
        # This is the line that actually runs our functions
        migrations.RunPython(load_data, reverse_code=reverse_data),
    ]